<?php

namespace AppBundle\Repository;

/**
 * AccuracyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccuracyRepository extends \Doctrine\ORM\EntityRepository
{
}
