<?php

namespace AppBundle\Repository;

/**
 * BraceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BraceRepository extends \Doctrine\ORM\EntityRepository
{
}
