<?php

namespace AppBundle\Repository;

/**
 * CountryCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
