<?php

namespace AppBundle\Repository;

/**
 * EqModeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EqModeRepository extends \Doctrine\ORM\EntityRepository
{
}
