<?php

namespace AppBundle\Repository;

/**
 * EqTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EqTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
