<?php

namespace AppBundle\Repository;

/**
 * MeasurementRangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeasurementRangeRepository extends \Doctrine\ORM\EntityRepository
{
}
