<?php

namespace AppBundle\Repository;

/**
 * ProcessConnectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcessConnectionRepository extends \Doctrine\ORM\EntityRepository
{
}
