<?php

namespace AppBundle\Repository;

/**
 * SpecialVersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialVersionRepository extends \Doctrine\ORM\EntityRepository
{
}
