<?php

namespace AppBundle\Repository;

/**
 * ValveUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValveUnitRepository extends \Doctrine\ORM\EntityRepository
{
}
