<?php

namespace AppBundle\Repository;

/**
 * WeldedElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeldedElementRepository extends \Doctrine\ORM\EntityRepository
{
}
