app_brace:
    resource: "@AppBundle/Controller/BraceController.php"
    type:     annotation

app_welded_element:
    resource: "@AppBundle/Controller/WeldedElementController.php"
    type:     annotation

app_valve_unit:
    resource: "@AppBundle/Controller/ValveUnitController.php"
    type:     annotation

app_process_connection:
    resource: "@AppBundle/Controller/ProcessConnectionController.php"
    type:     annotation

app_body_type:
    resource: "@AppBundle/Controller/BodyTypeController.php"
    type:     annotation

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
